/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

/**
 *
 * @author Win -8
 */
public class cashier extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public cashier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        j3 = new javax.swing.JRadioButton();
        j4 = new javax.swing.JRadioButton();
        j5 = new javax.swing.JRadioButton();
        j6 = new javax.swing.JRadioButton();
        j7 = new javax.swing.JRadioButton();
        j8 = new javax.swing.JRadioButton();
        j9 = new javax.swing.JRadioButton();
        j10 = new javax.swing.JRadioButton();
        j13 = new javax.swing.JRadioButton();
        j14 = new javax.swing.JRadioButton();
        j17 = new javax.swing.JRadioButton();
        j18 = new javax.swing.JRadioButton();
        j12 = new javax.swing.JRadioButton();
        j11 = new javax.swing.JRadioButton();
        j15 = new javax.swing.JRadioButton();
        j16 = new javax.swing.JRadioButton();
        j19 = new javax.swing.JRadioButton();
        j20 = new javax.swing.JRadioButton();
        j23 = new javax.swing.JRadioButton();
        j24 = new javax.swing.JRadioButton();
        j27 = new javax.swing.JRadioButton();
        j28 = new javax.swing.JRadioButton();
        j2 = new javax.swing.JRadioButton();
        j29 = new javax.swing.JRadioButton();
        j30 = new javax.swing.JRadioButton();
        j25 = new javax.swing.JRadioButton();
        j26 = new javax.swing.JRadioButton();
        j22 = new javax.swing.JRadioButton();
        j21 = new javax.swing.JRadioButton();
        j31 = new javax.swing.JRadioButton();
        j32 = new javax.swing.JRadioButton();
        j33 = new javax.swing.JRadioButton();
        j34 = new javax.swing.JRadioButton();
        j35 = new javax.swing.JRadioButton();
        j36 = new javax.swing.JRadioButton();
        j37 = new javax.swing.JRadioButton();
        j38 = new javax.swing.JRadioButton();
        j39 = new javax.swing.JRadioButton();
        j40 = new javax.swing.JRadioButton();
        j41 = new javax.swing.JRadioButton();
        j42 = new javax.swing.JRadioButton();
        j43 = new javax.swing.JRadioButton();
        j44 = new javax.swing.JRadioButton();
        j51 = new javax.swing.JRadioButton();
        j50 = new javax.swing.JRadioButton();
        j49 = new javax.swing.JRadioButton();
        j48 = new javax.swing.JRadioButton();
        j46 = new javax.swing.JRadioButton();
        j45 = new javax.swing.JRadioButton();
        j52 = new javax.swing.JRadioButton();
        j55 = new javax.swing.JRadioButton();
        j56 = new javax.swing.JRadioButton();
        j57 = new javax.swing.JRadioButton();
        j58 = new javax.swing.JRadioButton();
        j59 = new javax.swing.JRadioButton();
        j60 = new javax.swing.JRadioButton();
        j61 = new javax.swing.JRadioButton();
        j63 = new javax.swing.JRadioButton();
        j62 = new javax.swing.JRadioButton();
        j64 = new javax.swing.JRadioButton();
        j68 = new javax.swing.JRadioButton();
        j67 = new javax.swing.JRadioButton();
        j66 = new javax.swing.JRadioButton();
        j65 = new javax.swing.JRadioButton();
        j69 = new javax.swing.JRadioButton();
        j70 = new javax.swing.JRadioButton();
        j71 = new javax.swing.JRadioButton();
        j72 = new javax.swing.JRadioButton();
        j73 = new javax.swing.JRadioButton();
        j74 = new javax.swing.JRadioButton();
        j54 = new javax.swing.JRadioButton();
        j1 = new javax.swing.JRadioButton();
        j75 = new javax.swing.JRadioButton();
        j76 = new javax.swing.JRadioButton();
        j77 = new javax.swing.JRadioButton();
        j78 = new javax.swing.JRadioButton();
        j79 = new javax.swing.JRadioButton();
        j81 = new javax.swing.JRadioButton();
        j80 = new javax.swing.JRadioButton();
        j82 = new javax.swing.JRadioButton();
        j53 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j3.setContentAreaFilled(false);
        j3.setBounds(60, 30, 21, 23);
        jLayeredPane2.add(j3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j4.setContentAreaFilled(false);
        j4.setBounds(60, 10, 21, 23);
        jLayeredPane2.add(j4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j5.setContentAreaFilled(false);
        j5.setBounds(80, 30, 21, 23);
        jLayeredPane2.add(j5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j6.setContentAreaFilled(false);
        j6.setBounds(90, 50, 21, 23);
        jLayeredPane2.add(j6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j7.setContentAreaFilled(false);
        j7.setBounds(110, 70, 21, 23);
        jLayeredPane2.add(j7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j8.setContentAreaFilled(false);
        j8.setBounds(110, 50, 21, 23);
        jLayeredPane2.add(j8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j9.setContentAreaFilled(false);
        j9.setBounds(110, 30, 21, 23);
        jLayeredPane2.add(j9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j10.setContentAreaFilled(false);
        j10.setBounds(110, 10, 21, 23);
        jLayeredPane2.add(j10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j13.setContentAreaFilled(false);
        j13.setBounds(140, 10, 21, 23);
        jLayeredPane2.add(j13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j14.setContentAreaFilled(false);
        j14.setBounds(140, 30, 21, 23);
        jLayeredPane2.add(j14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j17.setContentAreaFilled(false);
        j17.setBounds(140, 50, 21, 23);
        jLayeredPane2.add(j17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j18.setContentAreaFilled(false);
        j18.setBounds(140, 70, 21, 23);
        jLayeredPane2.add(j18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j12.setContentAreaFilled(false);
        j12.setBounds(160, 10, 21, 23);
        jLayeredPane2.add(j12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j11.setContentAreaFilled(false);
        j11.setBounds(180, 10, 21, 23);
        jLayeredPane2.add(j11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j15.setContentAreaFilled(false);
        j15.setBounds(160, 40, 21, 23);
        jLayeredPane2.add(j15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j16.setContentAreaFilled(false);
        j16.setBounds(180, 40, 21, 23);
        jLayeredPane2.add(j16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j19.setContentAreaFilled(false);
        j19.setBounds(160, 70, 21, 23);
        jLayeredPane2.add(j19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j20.setContentAreaFilled(false);
        j20.setBounds(180, 70, 21, 23);
        jLayeredPane2.add(j20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j23.setContentAreaFilled(false);
        j23.setBounds(210, 10, 21, 23);
        jLayeredPane2.add(j23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j24.setContentAreaFilled(false);
        j24.setBounds(210, 30, 21, 23);
        jLayeredPane2.add(j24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j27.setContentAreaFilled(false);
        j27.setBounds(210, 50, 21, 23);
        jLayeredPane2.add(j27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j28.setContentAreaFilled(false);
        j28.setBounds(210, 70, 21, 23);
        jLayeredPane2.add(j28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j2.setContentAreaFilled(false);
        j2.setBounds(60, 50, 21, 23);
        jLayeredPane2.add(j2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j29.setContentAreaFilled(false);
        j29.setBounds(230, 70, 21, 23);
        jLayeredPane2.add(j29, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j30.setContentAreaFilled(false);
        j30.setBounds(250, 70, 21, 23);
        jLayeredPane2.add(j30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j25.setContentAreaFilled(false);
        j25.setBounds(230, 40, 21, 23);
        jLayeredPane2.add(j25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j26.setContentAreaFilled(false);
        j26.setBounds(250, 40, 21, 23);
        jLayeredPane2.add(j26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j22.setContentAreaFilled(false);
        j22.setBounds(230, 10, 21, 23);
        jLayeredPane2.add(j22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j21.setContentAreaFilled(false);
        j21.setBounds(250, 10, 21, 23);
        jLayeredPane2.add(j21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j31.setContentAreaFilled(false);
        j31.setBounds(270, 10, 21, 23);
        jLayeredPane2.add(j31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j32.setContentAreaFilled(false);
        j32.setBounds(270, 30, 21, 23);
        jLayeredPane2.add(j32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j33.setContentAreaFilled(false);
        j33.setBounds(270, 50, 21, 23);
        jLayeredPane2.add(j33, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j34.setContentAreaFilled(false);
        j34.setBounds(270, 70, 21, 23);
        jLayeredPane2.add(j34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j35.setContentAreaFilled(false);
        j35.setBounds(290, 70, 21, 23);
        jLayeredPane2.add(j35, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j36.setContentAreaFilled(false);
        j36.setBounds(310, 70, 21, 23);
        jLayeredPane2.add(j36, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j37.setContentAreaFilled(false);
        j37.setBounds(330, 70, 21, 23);
        jLayeredPane2.add(j37, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j38.setContentAreaFilled(false);
        j38.setBounds(340, 50, 21, 23);
        jLayeredPane2.add(j38, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j39.setContentAreaFilled(false);
        j39.setBounds(350, 30, 21, 23);
        jLayeredPane2.add(j39, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j40.setContentAreaFilled(false);
        j40.setBounds(360, 10, 21, 23);
        jLayeredPane2.add(j40, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j41.setContentAreaFilled(false);
        j41.setBounds(370, 30, 21, 23);
        jLayeredPane2.add(j41, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j42.setContentAreaFilled(false);
        j42.setBounds(380, 50, 21, 23);
        jLayeredPane2.add(j42, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j43.setContentAreaFilled(false);
        j43.setBounds(390, 70, 21, 23);
        jLayeredPane2.add(j43, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j44.setContentAreaFilled(false);
        j44.setBounds(360, 50, 21, 23);
        jLayeredPane2.add(j44, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j51.setContentAreaFilled(false);
        j51.setBounds(410, 70, 21, 23);
        jLayeredPane2.add(j51, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j50.setContentAreaFilled(false);
        j50.setBounds(410, 50, 21, 23);
        jLayeredPane2.add(j50, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j49.setContentAreaFilled(false);
        j49.setBounds(410, 30, 21, 23);
        jLayeredPane2.add(j49, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j48.setContentAreaFilled(false);
        j48.setBounds(410, 10, 21, 23);
        jLayeredPane2.add(j48, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j46.setContentAreaFilled(false);
        j46.setBounds(430, 10, 21, 23);
        jLayeredPane2.add(j46, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j45.setContentAreaFilled(false);
        j45.setBounds(450, 10, 21, 23);
        jLayeredPane2.add(j45, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j52.setContentAreaFilled(false);
        j52.setBounds(430, 70, 21, 23);
        jLayeredPane2.add(j52, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j55.setContentAreaFilled(false);
        j55.setBounds(450, 40, 21, 23);
        jLayeredPane2.add(j55, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j56.setContentAreaFilled(false);
        j56.setBounds(430, 40, 21, 23);
        jLayeredPane2.add(j56, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j57.setContentAreaFilled(false);
        j57.setBounds(480, 10, 21, 23);
        jLayeredPane2.add(j57, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j58.setContentAreaFilled(false);
        j58.setBounds(500, 10, 21, 23);
        jLayeredPane2.add(j58, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j59.setContentAreaFilled(false);
        j59.setBounds(520, 10, 21, 23);
        jLayeredPane2.add(j59, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j60.setContentAreaFilled(false);
        j60.setBounds(500, 30, 21, 23);
        jLayeredPane2.add(j60, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j61.setContentAreaFilled(false);
        j61.setBounds(500, 50, 21, 23);
        jLayeredPane2.add(j61, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j63.setContentAreaFilled(false);
        j63.setBounds(500, 70, 21, 23);
        jLayeredPane2.add(j63, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j62.setContentAreaFilled(false);
        j62.setBounds(480, 70, 21, 23);
        jLayeredPane2.add(j62, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j64.setContentAreaFilled(false);
        j64.setBounds(520, 70, 21, 23);
        jLayeredPane2.add(j64, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j68.setContentAreaFilled(false);
        j68.setBounds(540, 10, 21, 23);
        jLayeredPane2.add(j68, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j67.setContentAreaFilled(false);
        j67.setBounds(540, 30, 21, 23);
        jLayeredPane2.add(j67, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j66.setContentAreaFilled(false);
        j66.setBounds(540, 50, 21, 23);
        jLayeredPane2.add(j66, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j65.setContentAreaFilled(false);
        j65.setBounds(540, 70, 21, 23);
        jLayeredPane2.add(j65, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j69.setContentAreaFilled(false);
        j69.setBounds(560, 10, 21, 23);
        jLayeredPane2.add(j69, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j70.setContentAreaFilled(false);
        j70.setBounds(580, 10, 21, 23);
        jLayeredPane2.add(j70, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j71.setContentAreaFilled(false);
        j71.setBounds(580, 30, 21, 23);
        jLayeredPane2.add(j71, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j72.setContentAreaFilled(false);
        j72.setBounds(560, 40, 21, 23);
        jLayeredPane2.add(j72, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j73.setContentAreaFilled(false);
        j73.setBounds(570, 60, 21, 23);
        jLayeredPane2.add(j73, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j74.setContentAreaFilled(false);
        j74.setBounds(580, 70, 21, 23);
        jLayeredPane2.add(j74, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j54.setContentAreaFilled(false);
        j54.setBounds(450, 60, 21, 23);
        jLayeredPane2.add(j54, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j1.setContentAreaFilled(false);
        j1.setBounds(60, 70, 21, 23);
        jLayeredPane2.add(j1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j75.setContentAreaFilled(false);
        j75.setBounds(600, 10, 21, 23);
        jLayeredPane2.add(j75, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j76.setContentAreaFilled(false);
        j76.setBounds(620, 10, 21, 23);
        jLayeredPane2.add(j76, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j77.setContentAreaFilled(false);
        j77.setBounds(640, 10, 21, 23);
        jLayeredPane2.add(j77, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j78.setContentAreaFilled(false);
        j78.setBounds(620, 30, 21, 23);
        jLayeredPane2.add(j78, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j79.setContentAreaFilled(false);
        j79.setBounds(620, 50, 21, 23);
        jLayeredPane2.add(j79, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j81.setContentAreaFilled(false);
        j81.setBounds(620, 70, 21, 23);
        jLayeredPane2.add(j81, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j80.setContentAreaFilled(false);
        j80.setBounds(600, 70, 21, 23);
        jLayeredPane2.add(j80, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j82.setContentAreaFilled(false);
        j82.setBounds(640, 70, 21, 23);
        jLayeredPane2.add(j82, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j53.setContentAreaFilled(false);
        j53.setBounds(450, 70, 21, 23);
        jLayeredPane2.add(j53, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(50, 20, 710, 100);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("GRN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(490, 270, 140, 40);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Invoice");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(210, 390, 130, 40);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/theme.jpg"))); // NOI18N
        jLabel1.setBounds(0, 0, 800, 600);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new GRN().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Invoice().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashier().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton j1;
    private javax.swing.JRadioButton j10;
    private javax.swing.JRadioButton j11;
    private javax.swing.JRadioButton j12;
    private javax.swing.JRadioButton j13;
    private javax.swing.JRadioButton j14;
    private javax.swing.JRadioButton j15;
    private javax.swing.JRadioButton j16;
    private javax.swing.JRadioButton j17;
    private javax.swing.JRadioButton j18;
    private javax.swing.JRadioButton j19;
    private javax.swing.JRadioButton j2;
    private javax.swing.JRadioButton j20;
    private javax.swing.JRadioButton j21;
    private javax.swing.JRadioButton j22;
    private javax.swing.JRadioButton j23;
    private javax.swing.JRadioButton j24;
    private javax.swing.JRadioButton j25;
    private javax.swing.JRadioButton j26;
    private javax.swing.JRadioButton j27;
    private javax.swing.JRadioButton j28;
    private javax.swing.JRadioButton j29;
    private javax.swing.JRadioButton j3;
    private javax.swing.JRadioButton j30;
    private javax.swing.JRadioButton j31;
    private javax.swing.JRadioButton j32;
    private javax.swing.JRadioButton j33;
    private javax.swing.JRadioButton j34;
    private javax.swing.JRadioButton j35;
    private javax.swing.JRadioButton j36;
    private javax.swing.JRadioButton j37;
    private javax.swing.JRadioButton j38;
    private javax.swing.JRadioButton j39;
    private javax.swing.JRadioButton j4;
    private javax.swing.JRadioButton j40;
    private javax.swing.JRadioButton j41;
    private javax.swing.JRadioButton j42;
    private javax.swing.JRadioButton j43;
    private javax.swing.JRadioButton j44;
    private javax.swing.JRadioButton j45;
    private javax.swing.JRadioButton j46;
    private javax.swing.JRadioButton j48;
    private javax.swing.JRadioButton j49;
    private javax.swing.JRadioButton j5;
    private javax.swing.JRadioButton j50;
    private javax.swing.JRadioButton j51;
    private javax.swing.JRadioButton j52;
    private javax.swing.JRadioButton j53;
    private javax.swing.JRadioButton j54;
    private javax.swing.JRadioButton j55;
    private javax.swing.JRadioButton j56;
    private javax.swing.JRadioButton j57;
    private javax.swing.JRadioButton j58;
    private javax.swing.JRadioButton j59;
    private javax.swing.JRadioButton j6;
    private javax.swing.JRadioButton j60;
    private javax.swing.JRadioButton j61;
    private javax.swing.JRadioButton j62;
    private javax.swing.JRadioButton j63;
    private javax.swing.JRadioButton j64;
    private javax.swing.JRadioButton j65;
    private javax.swing.JRadioButton j66;
    private javax.swing.JRadioButton j67;
    private javax.swing.JRadioButton j68;
    private javax.swing.JRadioButton j69;
    private javax.swing.JRadioButton j7;
    private javax.swing.JRadioButton j70;
    private javax.swing.JRadioButton j71;
    private javax.swing.JRadioButton j72;
    private javax.swing.JRadioButton j73;
    private javax.swing.JRadioButton j74;
    private javax.swing.JRadioButton j75;
    private javax.swing.JRadioButton j76;
    private javax.swing.JRadioButton j77;
    private javax.swing.JRadioButton j78;
    private javax.swing.JRadioButton j79;
    private javax.swing.JRadioButton j8;
    private javax.swing.JRadioButton j80;
    private javax.swing.JRadioButton j81;
    private javax.swing.JRadioButton j82;
    private javax.swing.JRadioButton j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    // End of variables declaration//GEN-END:variables
}
