/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import properties.characterProperty;
import properties.focusManager;

/**
 *
 * @author Win -8
 */
public class Neelagiri extends javax.swing.JFrame {

    /**
     * Creates new form Neelagiri
     */
    public Neelagiri() {
        initComponents();
        controls();
        myTimer();
        joptionPane();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        User_Registration = new javax.swing.JLayeredPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        imageur = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jradioFemale = new javax.swing.JRadioButton();
        jradioMale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txt_contactNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_lName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_fName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        USER_REGISTRATION = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextArea();
        time = new javax.swing.JLabel();
        user_regBG = new javax.swing.JLabel();
        Account_Registration = new javax.swing.JLayeredPane();
        jPasswordField1 = new javax.swing.JPasswordField();
        status = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        USER_REGISTRATION1 = new javax.swing.JLabel();
        acc_regBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        User_Registration.setPreferredSize(new java.awt.Dimension(800, 600));

        imageur.setBounds(0, 0, 160, 150);
        jDesktopPane1.add(imageur, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane1.setBounds(590, 270, 160, 150);
        User_Registration.add(jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(610, 490, 130, 30);
        User_Registration.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(380, 490, 160, 30);
        User_Registration.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("Image :");
        jLabel10.setBounds(430, 270, 90, 30);
        User_Registration.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(jradioFemale);
        jradioFemale.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jradioFemale.setText("Female");
        jradioFemale.setContentAreaFilled(false);
        jradioFemale.setBounds(210, 270, 140, 31);
        User_Registration.add(jradioFemale, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(jradioMale);
        jradioMale.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jradioMale.setText("Male");
        jradioMale.setContentAreaFilled(false);
        jradioMale.setBounds(210, 220, 160, 31);
        User_Registration.add(jradioMale, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Gender :");
        jLabel9.setBounds(40, 220, 130, 30);
        User_Registration.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txt_contactNo.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        txt_contactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contactNoKeyTyped(evt);
            }
        });
        txt_contactNo.setBounds(590, 210, 180, 30);
        User_Registration.add(txt_contactNo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Contact No :");
        jLabel6.setBounds(430, 210, 140, 30);
        User_Registration.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txt_lName.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        txt_lName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lNameActionPerformed(evt);
            }
        });
        txt_lName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_lNameKeyReleased(evt);
            }
        });
        txt_lName.setBounds(590, 160, 180, 30);
        User_Registration.add(txt_lName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Last Name:");
        jLabel7.setBounds(430, 160, 170, 30);
        User_Registration.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txt_fName.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        txt_fName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fNameKeyReleased(evt);
            }
        });
        txt_fName.setBounds(210, 160, 170, 30);
        User_Registration.add(txt_fName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("First Name :");
        jLabel8.setBounds(40, 160, 170, 30);
        User_Registration.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Address :");
        jLabel4.setBounds(40, 330, 130, 30);
        User_Registration.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txt_nic.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        txt_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nicKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nicKeyPressed(evt);
            }
        });
        txt_nic.setBounds(210, 110, 170, 30);
        User_Registration.add(txt_nic, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("NIC :");
        jLabel5.setBounds(40, 110, 170, 30);
        User_Registration.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        USER_REGISTRATION.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        USER_REGISTRATION.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        USER_REGISTRATION.setText("User Registration");
        USER_REGISTRATION.setBounds(0, 0, 800, 50);
        User_Registration.add(USER_REGISTRATION, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txt_address.setColumns(20);
        txt_address.setRows(5);
        jScrollPane1.setViewportView(txt_address);

        jScrollPane1.setBounds(210, 330, 330, 90);
        User_Registration.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        time.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        time.setBounds(430, 110, 340, 30);
        User_Registration.add(time, javax.swing.JLayeredPane.DEFAULT_LAYER);

        user_regBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/theme.jpg"))); // NOI18N
        user_regBG.setBounds(0, 0, 800, 600);
        User_Registration.add(user_regBG, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Account_Registration.setPreferredSize(new java.awt.Dimension(800, 600));
        jPasswordField1.setBounds(380, 220, 170, 30);
        Account_Registration.add(jPasswordField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        status.setBounds(180, 130, 220, 50);
        Account_Registration.add(status, javax.swing.JLayeredPane.DEFAULT_LAYER);
        image.setBounds(50, 60, 120, 120);
        Account_Registration.add(image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setFont(new java.awt.Font("Cordia New", 0, 36)); // NOI18N
        jLabel12.setText("Password :");
        jLabel12.setBounds(220, 220, 140, 30);
        Account_Registration.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField7.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jTextField7.setBounds(380, 150, 170, 30);
        Account_Registration.add(jTextField7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setFont(new java.awt.Font("Cordia New", 0, 36)); // NOI18N
        jLabel11.setText("Username :");
        jLabel11.setBounds(220, 150, 140, 30);
        Account_Registration.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        USER_REGISTRATION1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        USER_REGISTRATION1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        USER_REGISTRATION1.setText("Account Registration");
        USER_REGISTRATION1.setBounds(0, 0, 800, 50);
        Account_Registration.add(USER_REGISTRATION1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        acc_regBG.setBounds(0, 0, 800, 580);
        Account_Registration.add(acc_regBG, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Account_Registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(User_Registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Account_Registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(User_Registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        User_Registration.setVisible(false);
        Account_Registration.setVisible(true);
        if(jradioMale.isSelected()){
            gender="male";
        }else if(jradioFemale.isSelected()){
            gender="female";
        }
        try {
           db.con().createStatement().executeUpdate("INSERT INTO usertype VALUES('"+wID+"','"+txt_nic.getText()+"','"+txt_fName.getText()+"','"+txt_lName.getText()+"','"+gender+"','"+txt_address.getText()+"','"+txt_contactNo.getText()+"','"+jpath+"')");
           USER_REGISTRATION.setVisible(false);
           Account_Registration.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nicKeyTyped
        // TODO add your handling code here:
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')) {
            evt.consume();
        } else {
            //evt.consume();
        }
        if (txt_nic.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nicKeyTyped

    private void txt_nicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nicKeyPressed
        // TODO add your handling code here:
        new focusManager().textFieldsNext(evt, txt_nic, null);
    }//GEN-LAST:event_txt_nicKeyPressed

    private void txt_fNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fNameKeyReleased
        // TODO add your handling code here:
        new characterProperty().letterUppercase(txt_fName, 0);
    }//GEN-LAST:event_txt_fNameKeyReleased

    private void txt_lNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lNameKeyReleased
        // TODO add your handling code here:
        new characterProperty().letterUppercase(txt_lName, 0);
    }//GEN-LAST:event_txt_lNameKeyReleased

    private void txt_contactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contactNoKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
        } else {
            evt.consume();
        }
        if (txt_contactNo.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_contactNoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            JFileChooser jf = new JFileChooser();
            jf.showOpenDialog(this);
            File f = jf.getSelectedFile();
            String path = f.getAbsolutePath();
            jpath = path.replace("\\", "/");
            //-----------------set image to lable
            File ff = new File(path);
            Image img = ImageIO.read(ff);
            img = img.getScaledInstance(imageur.getWidth(), imageur.getHeight(), Image.SCALE_SMOOTH);
            imageur.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_lNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Neelagiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Neelagiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Neelagiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Neelagiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            javax.swing.UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            com.birosoft.liquid.LiquidLookAndFeel.setLiquidDecorations(true, "mac");
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Neelagiri().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Account_Registration;
    private javax.swing.JLabel USER_REGISTRATION;
    private javax.swing.JLabel USER_REGISTRATION1;
    private javax.swing.JLayeredPane User_Registration;
    private javax.swing.JLabel acc_regBG;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel image;
    private javax.swing.JLabel imageur;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JRadioButton jradioFemale;
    private javax.swing.JRadioButton jradioMale;
    private javax.swing.JLabel status;
    private javax.swing.JLabel time;
    private javax.swing.JTextArea txt_address;
    private javax.swing.JTextField txt_contactNo;
    private javax.swing.JTextField txt_fName;
    private javax.swing.JTextField txt_lName;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JLabel user_regBG;
    // End of variables declaration//GEN-END:variables

    private void controls() {
        Account_Registration.setVisible(false);
    }
    String jpath;

    public void myTimer() {
        Timer t;
        t = new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sd = new SimpleDateFormat(" hh:mm:ss a     yyyy-MM-dd");
                time.setText(sd.format(d));
            }
        });
        t.start();
    }

    public void joptionPane() {
        String getPosition = JOptionPane.showInputDialog(this, "Type the Position");
        if (getPosition.equals("manager")) {
            position = "manager";
        } else if (getPosition.equals("supplier")) {
            position = "suppler";
        } else if (getPosition.equals("cashier")) {
            position = "cashier";
        } else if (getPosition.equals("waiter")) {
            position = "waiter";
            wID = JOptionPane.showInputDialog("Enter waiter ID");
        }
    }
    String position;
    String wID;
    String gender;
}
